### ISSUE TITLE
Use the Razor engine to generate the email body for notifications

### ISSUE THREAD

**Issue by erwindevreugd** [csharpfritz/CoreWiki#169]

**Comment by parithon** [comment]
Looks like you might want to look at Microsoft.AspNetCore.Razor.Language.dll and the [RazorTemplateEngine](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.razor.language.razortemplateengine?view=aspnetcore-2.1) class.

**Comment by JustCallMeAD** [comment]
Wouldn't using Razor for the email templates be a security issue? 

I think the reason a basic html parser was used in the first place was so that (in the future) you could allow site editors / admins to edit the email templates without giving them access to Razor (this is a security risk).

Maybe it would be worth considering looking at how Orchard does things using Liquid (https://orchardcore.readthedocs.io/en/dev/OrchardCore.Modules/OrchardCore.Liquid/README/). 

Based on Shopify templating engine: Safe, customer-facing template language for flexible web apps - https://shopify.github.io/liquid/

If you use something like liquid then it can also be used for other type of templates such as site / layout templates :)

**Comment by black-byte** [comment]
You can checkout also scriban at https://github.com/lunet-io/scriban

**Comment by Franklin89** [comment]
@JustCallMeAD could you ellaborate on the security concern a bit?
