### ISSUE TITLE
Code Comments

### ISSUE THREAD

**Issue by emo333** [csharpfritz/CoreWiki#209]
Do we want to comment our code throughout CoreWiki in places where the code does not obviously convey what it's purpose is?  Just thinking since CoreWiki's purpose is for people to learn ASP.NET Core, it would be beneficial for people who may have not been following the evolution of the project.

**Comment by ashleybroughton** [comment]
I personally am of the opinion that comments are a code smell. If something doesn't make sense by looking at the code, then it needs to be refactored to make sense.

The problem with comments is that they do not always reflect the current state of the code (people may forget to update them, they may not be deleted, or they may not be correct in the first place).

The code is always the best documentation of what is currently happening within the system.

**Comment by erwindevreugd** [comment]
I agree with @ashleybroughton. I can also see @emo333 point where complicated code is concerned. I do think that using summary tags to document the (public\internal) api surface can be helpful. More unit test of course would also be helpful.

**Comment by andrewcahill** [comment]
I also fully agree with Ashley and believe code should be self documenting of their actions and intent. My main view around this are around reasons for choosing a certain 'path' such as tool,library, pattern etc. over another this is typically never documented and clear to the new developer of the why rather than the what. These are usually discussions at the time of development. A thought I had was maybe at a certain point there is a choice being discussed for a period of time of choosing a certain 'path' that you could reference in code the video and time the discussion occurred - just a thought.
